{
 "title": "demo",
 "description": "demo dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "myTimedMethod接口调用总次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "my_timed_method_seconds_count{instance=\"$instance\", application=\"$application\", uri=\"/myTimedMethod\"}",
     "legendFormat": "myTimedMethod接口调用总次数"
    }
   ]
  },
  {
   "title": "myTimedMethod接口调用总时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "my_timed_method_seconds_sum{instance=\"$instance\", application=\"$application\", uri=\"/myTimedMethod\"}",
     "legendFormat": "myTimedMethod接口调用总时间"
    }
   ]
  },
  {
   "title": "myTimedMethod接口调用最大时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "my_timed_method_seconds_max{instance=\"$instance\", application=\"$application\", uri=\"/myTimedMethod\"}",
     "legendFormat": "myTimedMethod接口调用最大时间"
    }
   ]
  },
  {
   "title": "myTimedMethod接口平均延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(my_timed_method_seconds_sum{instance=\"$instance\", application=\"$application\", uri=\"/myTimedMethod\"}[10s])/rate(my_timed_method_seconds_count{instance=\"$instance\", application=\"$application\", uri=\"/myTimedMethod\"}[10s])",
     "legendFormat": "myTimedMethod接口平均延迟"
    }
   ]
  },
  {
   "title": "myTimedMethod接口平均延迟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(my_timed_method_seconds_sum{instance=\"$instance\", application=\"$application\", uri=\"/myTimedMethod\"}[10s])/rate(my_timed_method_seconds_count{instance=\"$instance\", application=\"$application\", uri=\"/myTimedMethod\"}[10s])",
     "legendFormat": "myTimedMethod接口平均延迟"
    }
   ]
  },
  {
   "title": "队列大小",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "my_queue_size{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "队列大小"
    }
   ]
  },
  {
   "title": "次数统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "my_counter_total{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "次数统计"
    }
   ]
  }
 ]
}