global:
  #处理超时时间，默认为5min
  resolve_timeout: 5m
  # 邮箱smtp服务器
  smtp_smarthost: 'xxx'
  smtp_from: 'xxx'
  smtp_auth_username: 'xxx'
  smtp_auth_password: 'xxx'

# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  # 报警分组依据
  group_by: ['alertname', 'cluster', 'service']
  # 最初即第一次等待多久时间发送一组警报的通知
  group_wait: 10s
  # 在发送新警报前的等待时间
  group_interval: 5s
  # 发送重复警报的周期 对于email配置中，此项不可以设置过低，否则将会由于邮件发送太多频繁，被smtp服务器拒绝
  repeat_interval: 1m
  # 发送警报的接收者的名称，以下receivers name的名称
  # 启用email时改指向,示例先不发
  receiver: 'blackhole'

receivers:
  - name: 'blackhole'
  - name: 'email'
    # email_configs/webhook_configs/wechat_configs
    email_configs:
      # 接收警报的email配置
      - to: 'xxx'
        # 设定邮箱的内容模板
        html: '{{ template "alert.html" . }}'
        # 接收邮件的标题
        headers: { Subject: "[WARN] 报警邮件"}
        send_resolved: true
